<?php

namespace Infira\Console\Output;

use Symfony\Component\Console\Output\ConsoleSectionOutput;
use Symfony\Component\Console\Output\OutputInterface;

class ConsoleOutputWrapper
{
    private array $messages = [];
    private string $id;

    /**
     * @param string $title
     * @param 'full'|'mini' $type
     * @param ConsoleSectionOutput $section
     * @param int|null $maxItems
     */
    public function __construct(
        private string $title,
        private string $type,
        public ConsoleSectionOutput $section,
        private readonly ?int $maxItems = null
    ) {
        $this->id = uniqid('', true);
    }

    public function write(iterable|string $messages, bool $newline = false, int $options = OutputInterface::OUTPUT_NORMAL): void
    {
        $this->messages[] = [
            'type' => 'write',
            'messages' => $messages,
            'newline' => $newline,
            'options' => $options,
        ];
        $this->wrap();
    }

    public function writeRegion(ConsoleOutputWrapper $region): void
    {
        $this->messages[$region->id] = [
            'type' => 'write',
            'messages' => $region->section->getContent(),
            'newline' => false,
            'options' => OutputInterface::OUTPUT_NORMAL,
        ];
        $this->wrap();
    }

    public function writeln(iterable|string $messages, int $options = OutputInterface::OUTPUT_NORMAL): void
    {
        $this->write($messages, true, $options); // TODO: Change the autogenerated stub
    }

    private function wrap(): void
    {
        $this->section->clear();
        $wrapTitle = $this->title;
        [$left, $right] = $this->regionWrapSides($this->title, $this->type === 'full' ? '=' : '-');
        if ($this->type === 'full') {
            $wrapTitle = "<comment>$left</comment>".'['."<question> $wrapTitle </question>".']'."<comment>$right</comment>";
        }
        else if ($this->type === 'mini') {
            $wrapTitle = "<fg=magenta>$left</>".'['." $wrapTitle ".']'."<fg=magenta>$right</>";
        }

        $this->nl();
        $this->section->writeln($wrapTitle);
        $this->nl();

        if ($this->maxItems !== null && count($this->messages) > $this->maxItems) {
            array_shift($this->messages);
        }
        foreach ($this->messages as $msg) {
            $this->section->write($msg['messages'], $msg['newline'], $msg['options']);
        }
        $this->nl();
        $this->section->writeln($wrapTitle);
        $this->nl();
    }

    private function nl(): void
    {
        $this->section->writeln('', true);//empty line

    }

    /**
     * @return array{0:string,1:string}
     */
    private function regionWrapSides(string $title, string $char): array
    {
        $bracketLen = mb_strlen($title) + 4; // [ + space + title + space + ]
        $fill = max(6, 100 - $bracketLen);
        $left = intdiv($fill, 2);
        $right = $fill - $left;

        return [
            str_repeat($char, max($left, 25)),
            str_repeat($char, max($right, 25)),
        ];
    }
}
